---
namespace: mikewiebe
name: test-ci-publish
version: 2.1.13
readme: README.md
authors:
  - Mike Wiebe <mikewiebe>
description: Test publication of a collection via pipeline
license_file: LICENSE 
tags: [test ci]
dependencies:
  "ansible.netcommon": "*"
repository: https://github.com/en-hackathon/ansible-dcnm
